include @builddir@/mk/defs.mk
LIB=	bsd_compat
SRCS=	closefrom.c \
	file_at.c \
	humanize_number.c \
	strtonum.c \
	strnstr.c \
	funopen.c

LOCAL_CFLAGS=	-I$(top_srcdir)/compat \
		-I$(top_srcdir) \
		-I$(top_builddir)

VPATH=	$(top_srcdir)/compat

include $(MK)/static-lib.mk

