include @builddir@/mk/defs.mk
LIB=	bsd_compat
SRCS=	closefrom.c \
	file_at.c \
	humanize_number.c \
	strtonum.c \
	strnstr.c \
	funopen.c

LOCAL_CFLAGS=	-I$(top_srcdir)/compat \
		-I$(top_srcdir)

include $(MK)/static-lib.mk

