#!/bin/sh

usage() {
	echo "usage: $0 [-h] [-d YYYYMMDD] [-f file] [portname ...]" >&2
	# Respects EX_USAGE (sysexit.h)
	exit 64
}

while getopts "d:f:h" OPTS; do
	case ${OPTS} in
		d)
		DATE=${OPTARG}
		echo ${DATE} | egrep -q "^[0-9]{8}$"
		if [ $? -ne 0 ]; then
			echo "${DATE}: Bad date format" >&2
			usage
		fi
		shift; shift
		;;
		f)
		FILE=${OPTARG}
		test -f ${FILE} || (echo "${FILE}: No such file or directory" >&2; usage)
		test -r ${FILE} || (echo "${FILE}: Not readable" >&2; usage)
		shift; shift
		;;
		h)
		usage
		;;
		*)
		usage
		;;
	esac
done

: ${FILE:=/usr/ports/UPDATING}

if [ $# -eq 0 ]; then
#TODO: REPLACE with PKG_info
	ALLPORTS=`pkg_info -qoa | xargs echo`
else
	for PKG in "$*";do
		ORIGIN=`pkg_info -qo ${PKG}-*`
		if [ $? -eq 0 ]; then
			ALLPORTS="${ALLPORTS} ${ORIGIN}"
		else
			echo "${PKG}: No such packages installed" >&2
		fi
		unset ORIGIN
	done
fi
awk -v PORTS="${ALLPORTS}" 'BEGIN {
	split(PORTS,portorigin, " ");
	date_line="";
}
{
	if ($0 ~ /^\ \ AFFECTS.*$/) {
		for (i in portorigin) {
			if ( match($0, portorigin[i]) ) {
				found=1;
				print date_line
				print $0
				break;
			}
		}
	} else {
	date_line=$0;
	if ( found == 1) {
		if ($0 ~ /^[0-9]/) {
			found=0
		} else {
			print $0
		}
	}
}
}
' $FILE
#echo ${ALLPORTS}
exit 0
