#!/bin/sh

if [ $( id -u ) -ne 0 ]
then
	echo "This program needs to be run as root"
	return 77	# EX_PERM
fi

ARCH=$( uname -m )

for PKG in $( pkg_info -Ea )
do
	echo -n "Registering ${PKG}... "

	DB="/var/db/pkg/${PKG}"
	DESC="${DB}/+DESC"

	ORIGIN=$(pkg_info -qo ${PKG})
	PREFX=$(pkg_info -qp ${PKG})
	MAINTAINER=$( make -C /usr/ports/${ORIGIN} -V MAINTAINER )
	CATEGORIES=$( make -C /usr/ports/${ORIGIN} -V CATEGORIES | sed -e "s/ /,/g")
	LICENSES=$( make -C /usr/ports/${ORIGIN} -V LICENSE | sed -e "s/ /,/g")
	CONFLICTS=$( make -C /usr/ports/${ORIGIN} -V CONFLICTS)
	LICLOGIC=$(make -C /usr/ports/${ORIGIN} -V LICENSE_COMB )

	# +CONTENTS
	MDIR=$(mktemp -d /tmp/pkg2ngXXXXX)
	test -f ${DB}/+DISPLAY && cp -f ${DB}/+DISPLAY ${MDIR}
	test -f ${DB}/+MTREE_DIRS && cp -f ${DB}/+MTREE_DIRS ${MDIR}
	test -f ${DB}/+DESC && cp -f ${DB}/+DESC ${MDIR}
	MANIFEST=${MDIR}/+MANIFEST
	PLIST=${MDIR}/plist
	cp -f ${DB}/+INSTALL ${MDIR} 2>/dev/null
	echo "name: ${PKG%-*}" >> ${MANIFEST}
	echo "version: ${PKG##*-}" >> ${MANIFEST}
	echo "origin: ${ORIGIN}" >> ${MANIFEST}
	echo "comment: |" >> ${MANIFEST}
	echo -n "  " >> ${MANIFEST}
	cat ${DB}/+COMMENT >> ${MANIFEST}
	echo "maintainer: ${MAINTAINER}" >> ${MANIFEST}
	echo "prefix: ${PREFX##* }" >> ${MANIFEST}
	echo "licenselogic: ${LICLOGIC:-single}" >> ${MANIFEST}
	test -n "${LICENSES}" && echo "licenses: [${LICENSES}]" >> ${MANIFEST}
	echo "deps:" >> ${MANIFEST}
	pkg_info -qr ${PKG} | while read ignore dep; do
		deporigin=$(pkg_info -qo ${dep})
		echo -e "  ${dep%-*}: { origin: \"${deporigin}\", version: \"${dep##*-}\"}" >> ${MANIFEST}
	done
	egrep -v "^@(name|pkgdep|ignore|conflicts|display)" ${DB}/+CONTENTS >> ${PLIST}
	echo -n "conflicts: [" >> ${MANIFEST}
	for conflict in ${CONFLICTS}; do
		echo -n "\"$conflict\"," >> ${MANIFEST}
	done
	echo "]" >> ${MANIFEST}
	test -n "${CATEGORIES}" && echo "categories: [${CATEGORIES}]" >> ${MANIFEST}

	OPTIONS=""

	# register a package only if it's not registered already
	if pkg info -e ${ORIGIN}; then
		echo "package is already registered."
	else
		pkg register -l -m ${MDIR} -f ${PLIST} ${CMD_ARGS}
		if [ $? -ne 0 ]; then
			echo "failed."
			cat ${MANIFEST}
		else
			echo "done." ; rm -rf ${MANIFEST}
		fi
	fi

	rm -rf ${MDIR}
done

