#!/bin/sh

if [ $(id -u) -ne 0 ]
then
	echo "This program needs to be run as root"
	return 77	# EX_PERM
fi

ARCH=`uname -m`

for PKG in $(pkg_info -Ea)
do
	echo -n "Registering ${PKG}..."

	DB="/var/db/pkg/${PKG}"
	COMMENT=`cat ${DB}/+COMMENT`
	DESC="${DB}/+DESC"

	# +CONTENTS
	PLIST=`mktemp /tmp/pkg2ng.plist.XXXXXX`
	DEPENDS=`mktemp /tmp/pkg2ng.depends.XXXXXX`
	eval `awk -v pfile=${PLIST} -v dfile=${DEPENDS} '
	BEGIN{
		origin=""
		depends=""
		conflicts=""
	}
	{
		if ( $0 ~ /^@pkgdep/ ) {
			dep = $2
			getline
			orig=$2
			sub(/DEPORIGIN/,"",orig)
			print dep""orig >> dfile
		} else if ( $0 ~ /^@comment ORIGIN/ ) {
			origin=$2
			sub(/ORIGIN:/,"",origin)
		} else if ( $0 ~ /^[^@]/ ) {
			print $0 >> pfile
		} else if ( $0 ~ /^@exec/) {
			print $0 >> pfile
		} else if ( $0 ~ /^@unexec/) {
			print $0 >> pfile
		} else if ( $0 ~ /^@conflict/) {
			conflict=conflict" "$2
		} else if ( $0 ~ /^@cwd/) {
			print $0 >> pfile
		} else if ( $0 ~ /^@ignore/) {
			getline
		}
	}
	END{
		print "export ORIGIN=\""origin"\""
		print "export CONFLICTS=\""conflict"\""
	}
	' ${DB}/+CONTENTS`

	OPTIONS=""
	SCRIPTS=`ls ${DB}/+*INSTALL 2>/dev/null`

	MAINTAINER=`make -C /usr/ports/${ORIGIN} -V MAINTAINER`

	CMD_ARGS=""
	test -f ${DB}/+MTREE_DIRS && CMD_ARGS="${CMD_ARGS} -m ${DB}/+MTREE_DIRS"
	test -f ${DB}/+DISPLAY && CMD_ARGS="${CMD_ARGS} -M ${DB}/+DISPLAY"
	test -n "${CONFLICTS}" && CMD_ARGS="${CMD_ARGS} -C ${CONFLICTS}"
	test -n "${SCRIPTS}" && CMD_ARGS="${CMD_ARGS} -s ${SCRIPTS}"
	test -n "${OPTIONS}" && CMD_ARGS="${CMD_ARGS} -O ${OPTIONS}"

	pkg register -c "${COMMENT}" -d ${DESC} -p /usr/local -n ${PKG} \
	-P "`cat ${DEPENDS}`" \
	-o ${ORIGIN} -a ${ARCH} -r ${MAINTAINER} -f ${PLIST} ${CMD_ARGS}

	rm ${PLIST} ${DEPENDS}

	echo " done"
done
