#!/bin/sh

ARCH=`uname -m`

for PKG in `pkg_info | awk '{ print $1}'`
do
	echo -n "Registering ${PKG}..."

	DB="/var/db/pkg/${PKG}"
	COMMENT=`cat ${DB}/+COMMENT`
	DESC="${DB}/+DESC"
	MTREE="${DB}/+MTREE"

	# Should check for existence and add to CMD only if true...
	MESSAGE="${DB}/+DISPLAY"

	# +CONTENTS \o/
	DEPENDSF=`mktemp /tmp/pkg2ng.deps.XXXXXX`
	PLIST=`mktemp /tmp/pkg2ng.plist.XXXXXX`
	eval `awk -v dfile=${DEPENDSF} -v pfile=${PLIST} '
	BEGIN{
		origin=""
		conflicts=""
	}
	{
		if ( $0 ~ /^@pkgdep/ ) {
			dep = $2
			getline
			orig=$2
			sub(/DEPORIGIN/,"",orig)
			print dep""orig >> dfile
		} else if ( $0 ~ /^@comment ORIGIN/ ) {
			origin=$2
			sub(/ORIGIN:/,"",origin)
		} else if ( $0 ~ /^[^@]/ ) {
			print $0 >> pfile
		} else if ( $0 ~ /^@.*exec/) {
			print $0 >> pfile
		} else if ( $0 ~ /^@conflict/) {
			conflict=conflict" "$2
		} else if ( $0 ~ /^@cwd/) {
			print $0 >> pfile
		}
	}
	END{
		print "export ORIGIN=\""origin"\""
		print "export CONFLICTS=\""conflict"\""
	}
	' ${DB}/+CONTENTS`

	OPTIONS=""
	SCRIPTS=`ls ${DB}/+*INSTALL 2>/dev/null`

	MAINTAINER=`make -C /usr/ports/${ORIGIN} -V MAINTAINER`

	CMD="pkg register -c ${COMMENT} -d ${DESC} -p /usr/local -m ${MTREE} \
		-P "`cat ${DEPENDSF}`" -n ${PKG} -o ${ORIGIN} -C ${CONFLICTS} \
		-M ${MESSAGE} -s ${SCRIPTS} \
		-a ${ARCH} -r ${MAINTAINER} -O ${OPTIONS}"

	echo ${CMD}
	echo " done"
done
