.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.8
.\" $FreeBSD$
.\"
.Dd March 3, 2013
.Dt PKG-FETCH 8
.Os
.Sh NAME
.Nm "pkg fetch"
.Nd Fetches remote packages.
.Sh SYNOPSIS
.Nm
.Op Fl r Ar reponame
.Op Fl dgiqUxy
.Ar <pkg-name>
.Op ...
.Nm
.Op Fl r Ar reponame
.Op Fl dqUy
.Fl a
.Nm
.Op Fl r Ar reponame
.Op Fl dqUy
.Fl u
.Sh DESCRIPTION
.Nm
is used to download binary packages from a remote repository.
.Pp
One or more packages, or patterns can be specified.
.Pp
Repository catalogues will be updated automatically using
.Xr pkg-update 8 .
This can be disabled with the
.Fl U
flag.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl a
Fetch all packages.
.It Fl d
Fetch the package and its dependencies as well.
.It Fl g
Treat
.Ar <pkg-name>
as a shell glob pattern.
.It Fl i
Make the standard or regular expression
.Fl ( x )
matching against
.Ar pkg-name
case insensitive.
.It Fl L
Backwards compatbility flag for
.Fl U .
This is planned to be removed.
.It Fl q
Quiet mode.
Show less output.
.It Fl r Ar reponame
Fetches packages from the given
.Ar reponame
if multiple repo support is enabled.
See
.Xr pkg.conf 5 .
.It Fl u
Fetch all available updates for the currently installed packages.
.It Fl U
Skip updating the repository catalogues with
.Xr pkg-update 8 .
Use the local cache only.
.It Fl x
Treat
.Ar <pkg-name>
as a regular expression according to the "modern" or "extended" syntax
of
.Xr re_format 7 .
.It Fl y
Assume yes when asked for confirmation before fetching packages.
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr pkg.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It PKG_DBDIR
.El
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg.conf 5 ,
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-audit 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-check 8 ,
.Xr pkg-clean 8 ,
.Xr pkg-convert 8 ,
.Xr pkg-create 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-info 8 ,
.Xr pkg-install 8 ,
.Xr pkg-lock 8 ,
.Xr pkg-query 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xr pkg-rquery 8 ,
.Xr pkg-search 8 ,
.Xr pkg-set 8 ,
.Xr pkg-shell 8 ,
.Xr pkg-shlib 8 ,
.Xr pkg-stats 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8
