.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.8
.\" $FreeBSD$
.\"
.Dd March 26, 2012
.Dt PKG-INSTALL 8
.Os
.Sh NAME
.Nm "pkg install"
.Nd installs packages from remote package repositories
.Sh SYNOPSIS
.Nm
.Op Fl yqfgxX
.Ar <pkg-origin> <...>
.Sh DESCRIPTION
.Nm
is used for installation of packages from a remote package
repository database.
It can install multiple packages
specified on the command-line from multiple repositories.
.Pp
If a package is found to exists in more than one package
repository the first matching repository is the one that the
package will be first tried to be fetched from.
.Pp
If fetching from the repository fails for some reason the next
repository, which the package is found to exist is the one that is
tried until the package is fetched, or all repositories are tried.
.Pp
Multiple package repositories is activated only when the environment
variable
.Ev PACKAGESITE
is not defined.
.Pp
If
.Ev PACKAGESITE
is defined then only the repository to which it
points is the one that is used during the package installations.
.Pp
It is always good to update your package repositories first before
doing a remote installation using
.Nm
.Pp
In order to update your remote package repositories please refer to the
.Xr pkg-update 8
man page.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl y
Assume yes when asked for confirmation before package installation.
.It Fl g
Treat the package names as shell glob patterns.
.It Fl x
Treat the package names as regular expressions.
.It Fl X
Treat the package names as extended regular expressions.
.It Fl f
Force the reinstallation of the package if already installed.
.It Fl q
Force quiet output.
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr pkg.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It Ev ASSUME_ALWAYS_YES
.It Ev HANDLE_RC_SCRIPTS
.It Ev PACKAGESITE
.It Ev PKG_CACHEDIR
.It Ev PKG_DBDIR
.It Ev PKG_MULTIREPOS
.El
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-audit 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-check 8 ,
.Xr pkg-clean 8 ,
.Xr pkg-create 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-fetch 8 ,
.Xr pkg-info 8 ,
.Xr pkg-query 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xr pkg-search 8 ,
.Xr pkg-set 8,
.Xr pkg-shell 8 ,
.Xr pkg-shlib 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8 ,
.Xr pkg.conf 5
