.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd April 06, 2011
.Dt PKG-INFO 1
.Os
.Sh NAME
.Nm "pkg info"
.Nd displays information for installed packages
.Sh SYNOPSIS
.Nm
.Fl a
.Nm
.Op Fl egxXdrlsqO
.Ar <pkg-name>
.Nm
.Op Fl drlsq
.Fl F Ar <pkg-file>
.Sh DESCRIPTION
.Nm
is used for displaying information for installed packages.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl O
Search is done by origin of the package.
.Pp
< Added only for ports compatibility - To be completed >
.It Fl e
Returns 0 if
.Ar <pkg-name>
is installed and is registered in the database, otherwise returns 1.
Useful for checking if a package is installed or not from a 
script.
.It Fl g
Treat
.Ar <pkg-name>
as a shell glob pattern.
.It Fl x
Treat
.Ar <pkg-name>
as a regular expression.
.It Fl X
Treat
.Ar <pkg-name>
as an extended regular expression.
.It Fl d
Displays the dependencies of package
.Ar <pkg-name>
.It Fl r
Displays a list of packages on which
.Ar <pkg-name>
depends.
.It Fl l
Display all files installed by
.Ar <pkg-name>
.It Fl s
Display the total size of files installed by
.Ar <pkg-name>
.It Fl E
< Added only for ports compatibility >
.Pp
< Currently not implemented >
.It Fl q
Be ``quiet'' 
.It Fl o
Display
.Ar pkg-name
origin
.It Fl p
Display the installation prefix for each package
matching
.Ar <pkg-name>
.El
.Sh WARNING
.Sh ENVRIOMENT
The following envrioment variables affect the execution of
.Nm :
.Bl -tag -width ".Ev TMPDIR"
.El
.Sh FILES
.Sh SEE ALSO
.Xr pkg 1 ,
.Xr pkg-add 1 ,
.Xr pkg-autoremove 1 ,
.Xr pkg-search 1 ,
.Xr pkg-backup 1 ,
.Xr pkg-install 1 ,
.Xr pkg-delete 1 ,
.Xr pkg-create 1 ,
.Xr pkg-register 1 ,
.Xr pkg-repo 1 ,
.Xr pkg-update 1 ,
.Xr pkg-upgrade 1 ,
.Xr pkg-version 1 ,
.Xr pkg-which 1 ,
.Xr pkg.conf 5
.Sh AUTHORS AND CONTRIBUTORS
.Sh BUGS
