.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.8
.\" $FreeBSD$
.\"
.Dd February 16, 2012
.Dt PKG-SEARCH 8
.Os
.Sh NAME
.Nm "pkg search"
.Nd search package repository catalogues
.Sh SYNOPSIS
.Nm
.Op Fl egxX
.Op Fl "r repo"
.Op Fl "S search"
.Op Fl "L label"
.Op Fl "M mod"
.Ar pkg-name
.Nm
.Op Fl cDdefgopqXx
.Op Fl "r repo"
.Ar pkg-name
.Sh DESCRIPTION
.Nm
is used for searching package repository catalogues.
Packages available for installation can be matched by name, by name
and version, by origin or by text in the package comments or package
descriptions.
The output defaults to displaying the field matched by the search
term, but any of the searchable fields may be displayed.
The output may be modified to additionally show many other data
associated with the matched package available from the repository
catalogues.
.Pp
It is recommended to update the local copies of the repository
catalogues before running
.Nm .
See
.Xr pkg-update 8 .
Package repositories are defined in the
.Fa pkg.conf
file; see
.Xr pkg.conf 5.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl e
Match
.Ar pattern
exactly against the search field.
.It Fl g
Treat
.Ar pattern
as a shell glob pattern.
The globbing expression must match the entirety of the field being seached.
.It Fl x
Treat
.Ar pattern
as a regular expression.  This is the default.
Matches any substring of the search field unless explicit beginning
(^) and ending (?) anchor terms are used.
.It Fl X
Treat
.Ar pattern
as an extended regular expression.
.It Fl c
Search for
.Ar pattern
in the package comment one-line description.
.It Fl d
Search for
.Ar pattern
in the package desription.
.It Fl f
Displays full information about the matching packages.
.It Fl D
Displays the dependencies of
.Ar pattern
.It Fl s
Displays the size of the package
.It Fl q
Be ``quiet''.
Prints only the requested information without
displaying many hints.
.It Fl o
Displays
.Ar pattern
origin.
.It Fl p
Displays the installation prefix for each package matching
.Ar pattern
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr pkg.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It Ev PACKAGESITE
.It Ev PKG_MULTIREPOS
.El
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-audit 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-check 8 ,
.Xr pkg-clean 8 ,
.Xr pkg-create 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-fetch 8 ,
.Xr pkg-info 8 ,
.Xr pkg-install 8 ,
.Xr pkg-query 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xr pkg-rquery 8 ,
.Xr pkg-set 8 ,
.Xr pkg-shell 8 ,
.Xr pkg-shlib 8 ,
.Xr pkg-stats 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8 ,
.Xr pkg.conf 5
