.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd January 23, 2012
.Dt PKG-INSTALL 1
.Os
.Sh NAME
.Nm "pkg install"
.Nd installs packages from remote package repositories
.Sh SYNOPSIS
.Nm
.Op Fl ygxX
.Ar <pkg-origin> <...>
.Sh DESCRIPTION
.Nm
is used for installation of packages from a remote package
repository database. It can install multiple packages 
specified on the command-line from multiple repositories.
.Pp
If a package is found to exists in more than one package 
repository the first matching repository is the one that the
package will be first tried to be fetched from. 
.Pp
If fetching from the repository fails for some reason the next
repository, which the package is found to exist is the one that is
tried until the package is fetched, or all repositories are tried.
.Pp
Multiple package repositories is activated only when the environment
variable \fBPACKAGESITE\fP is not defined.
.Pp
If \fBPACKAGESITE\fP is defined then only the repository to which it
points is the one that is used during the package installations.
.Pp
It is always good to update your package repositories first before
doing a remote installation using
.Nm
.Pp
In order to update your remote package repositories please refer to the
.Xr pkg-update 1
man page.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl y
Assume yes when asked for confirmation before package installation.
.It Fl g
Treat the package names as shell glob patterns.
.It Fl x
Treat the package names as regular expressions.
.It Fl X
Treat the package names as extended regular expressions.
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm :
.Bl -tag -width ".Ev PACKAGESITE"
.It Ev PACKAGESITE
When \fBPACKAGESITE\fP is defined
.Nm
will only use the remote repository to which it points. Otherwise
.Nm
will work on multiple repositories as listed in the
.Xr pkg.conf 5
file. Please note that multiple remote repositories is still considered
highly experimental.
.It Ev ASSUME_ALWAYS_YES
When this option is set to
.Fa YES
pkgng will automatically assume "yes" to all questions
which require confirmation before doing anything, as if it
the
.Fl y
flag was specified.
.El
.Sh FILES
See 
.Xr pkg.conf 5
.El
.Sh SEE ALSO
.Xr pkg 1 ,
.Xr pkg-add 1 ,
.Xr pkg-autoremove 1 ,
.Xr pkg-search 1 ,
.Xr pkg-backup 1 ,
.Xr pkg-create 1 ,
.Xr pkg-delete 1 ,
.Xr pkg-info 1 ,
.Xr pkg-register 1 ,
.Xr pkg-repo 1 ,
.Xr pkg-update 1 ,
.Xr pkg-upgrade 1 ,
.Xr pkg-version 1 ,
.Xr pkg-which 1 ,
.Xr pkg.conf 5
