.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd April 06, 2011
.Dt PKG-UPDATE 1
.Os
.Sh NAME
.Nm "pkg update"
.Nd updates remote package repository databases
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is used for updating from remote package repository databases.
.Pp
The remote repository databases to be updated are defined in the
.Pa /etc/pkg/repositories
file.
A remote package repository definition is in the form of
.Fa name = url
where
.Ar url
points to the remote location of the package repository.
.Pp
It is always a good idea to update your remote package
repositories before doing a remote install via
.Xr pkg-install 1
or upgrades via
.Xr pkg-upgrade 1
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.El
.Sh WARNING
.Sh ENVRIOMENT
The following envrioment variables affect the execution of
.Nm :
.Bl -tag -width ".Ev PACKAGESITE"
.It Ev PACKAGESITE
When \fBPACKAGESITE\fP is defined
.Nm
will only use the remote repository to which it points. Otherwise
.Nm
will work on multiple repositories as listed in the
.Pa /etc/pkg/repositories
file. Please note that multiple remote repositories is still considered
highly experimental.
.El
.Sh FILES
.Bl -tag -width -".Pa /etc/pkg/repositories"
.It Pa /etc/pkg/repositories
Global repositories file. This file contains a pair of
.Fa name = url
entries, each describing a remote repository, from which
.Nm
will fetch. The file format of the file
is the same as described in
.Xr pkg.conf 5
Please refer to the included sample configuration file for example
definitions of remote repositories.
.El
.Sh SEE ALSO
.Xr pkg 1,
.Xr pkg-add 1,
.Xr pkg-autoremove 1,
.Xr pkg-backup 1,
.Xr pkg-create 1,
.Xr pkg-info 1,
.Xr pkg-install 1,
.Xr pkg-search 1,
.Xr pkg-register 1,
.Xr pkg-update 1,
.Xr pkg-upgrade 1,
.Xr pkg-version 1,
.Xr pkg-which 1,
.Xr pkg.conf 5
.Sh AUTHORS AND CONTRIBUTORS
.Sh BUGS
