.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.8
.\" $FreeBSD$
.\"
.Dd May 24, 2012
.Dt PKG-FETCH 8
.Os
.Sh NAME
.Nm "pkg fetch"
.Nd Fetches remote packages.
.Sh SYNOPSIS
.Nm
.Op Fl r Ar reponame
.Op Fl yqgxXadL
.Ar <pkg-name>
.Op ...
.Sh DESCRIPTION
.Nm
is used to download binary packages from a remote repository.
.Pp
One or more packages, or patterns can be specified.
.Pp
Repository catalogues will be updated automatically using
.Xr pkg-update 8 .
This can be disabled with the
.Fl L
flag.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl a
Fetch all packages.
.It Fl y
Assume yes when asked for confirmation before fetching packages.
.It Fl q
Quiet mode.
Show less output.
.It Fl r Ar reponame
Fetches packages from the given
.Ar reponame
if multiple repo support is enabled.
See
.Xr pkg.conf 5 .
.It Fl g
Treat
.Ar <pkg-name>
as a shell glob pattern.
.It Fl x
Treat
.Ar <pkg-name>
as a regular expression.
.It Fl X
Treat
.Ar <pkg-name>
as an extended regular expression.
.It Fl L
Don't auto update the remote database with
.Xr pkg-update 8 .
Use the local cache only.
.It Fl d
Fetch the package and its dependencies as well.
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr pkg.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It PKG_DBDIR
.El
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-audit 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-check 8 ,
.Xr pkg-clean 8 ,
.Xr pkg-create 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-info 8 ,
.Xr pkg-install 8 ,
.Xr pkg-query 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xr pkg-rquery 8 ,
.Xr pkg-search 8 ,
.Xr pkg-set 8 ,
.Xr pkg-shell 8 ,
.Xr pkg-shlib 8 ,
.Xr pkg-stats 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8 ,
.Xr pkg.conf 5
