.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 8. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd February 16, 2012
.Dt PKG-REPO 8
.Os
.Sh NAME
.Nm "pkg repo"
.Nd creates a package database repository
.Sh SYNOPSIS
.Nm
.Ar <repo-path> <rsa-key>
.Sh DESCRIPTION
.Nm
is used for creating package repositories of already
available packages.
.Nm
is usefull for creating a package repository database,
and then sharing it with other people.
.Pp
When
.Nm
is invoked it will create a package database file (repo.sqlite)
which then can be used for remote package installations
from
.Xr pkg-install 8 .
.Pp
When you want to create a package database repository you need to
specify at least the directory which contains packages in
.Ar <repo-path>
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr pkg.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It PUBKEY
.El
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-search 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-install 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-info 8 ,
.Xr pkg-register 8 ,
.Xr pkg-create 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8 ,
.Xr pkg.conf 5
