.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 8. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd February 16, 2012
.Dt PKG-INFO 8
.Os
.Sh NAME
.Nm "pkg info"
.Nd displays information for packages
.Sh SYNOPSIS
.Nm
.Ar <pkg-name>
.Nm
.Fl a
.Nm
.Op Fl egxXEdrlsqopOfRF
.Ar <pkg-name>
.Nm
.Op Fl drlsq
.Fl F Ar <pkg-file>
.Sh DESCRIPTION
.Nm
is used for displaying information for packages.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl a
Display all installed packages.
.It Fl f
Display full information about the packages matching
.Ar <pkg-name> .
.It Fl R
Display the full yaml (raw) about the packages matching
.Ar <pkg-name> .
.It Fl e
If
.Ar <pkg-name>
is installed and registered in the database, return 0, otherwise return 8.
Useful for checking whether the package is installed.
.It Fl g
Treat
.Ar <pkg-name>
as a shell glob pattern.
.It Fl x
Treat
.Ar <pkg-name>
as a regular expression.
.It Fl X
Treat
.Ar <pkg-name>
as an extended regular expression.
.It Fl d
Display the list of packages which depend on
.Ar <pkg-name> .
.It Fl r
Display the list of packages required by
.Ar <pkg-name> .
.It Fl l
Display all files installed by
.Ar <pkg-name> .
.It Fl s
Display the total size of files installed by
.Ar <pkg-name>
.It Fl q
Be
.Dq quiet .
Prints only the requested information without displaying many hints.
.It Fl O
Search is done by the
.Ar <pkg-name>
origin. Added only for Ports compatibility.
.Pp
.It Fl E
Currently not implemented. Added only for Ports compatibility.
.It Fl o
Display
.Ar <pkg-name>
origin.
.It Fl p
Display the installation prefix for each package matching
.Ar <pkg-name> .
.It Fl F Ar <pkg-file>
Displays information from the package archive
.Ar <pkg-file> .
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr pkg.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It PKG_DBDIR
.El
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-search 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-install 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-create 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8 ,
.Xr pkg.conf 5 ,
