.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 8. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.8
.\" $FreeBSD$
.\"
.Dd February 16, 2012
.Dt PKG-UPDATING 8
.Os
.Sh NAME
.Nm "pkg updating"
.Nd displays UPDATING entries of software packages
.Sh SYNOPSIS
.Nm
.Op Fl d Ar date
.Op Fl f Ar file
.Op Ar pkg-name ...
.Nm
.Sh DESCRIPTION
The
.Nm
command scans the installed ports and show all UPDATING entries that affect one
of the installed ports. Alternative a list of pkg-names could be passed.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Ar pkg-name ...
UPDATING entries for the named packages are displayed.
.It Fl d Ar date
Only entries newer than
.Ar date
are shown. Use a YYYYMMDD date format.
.It Fl f Ar file 
Defines a alternative location of the UPDATING
.Ar file .
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm :
.Bl -tag -width F1
.It Ev PORTSDIR
Location of the ports tree.
.El
.Sh EXAMPLES
Shows all entries of all installed ports:
.Dl % pkg updating
.Pp
Shows all entries of all installed ports since 2012-01-01:
.Dl % pkg updating -d 20120101
.Pp
Shows all entries for all apache and mysql ports:
.Dl % pkg updating apache mysql
.Pp
Shows all apache entries since 2012-01-01:
.Dl % pkg updating -d 20120101 apache
.Pp
Defines that the UPDATING file is in /tmp and shows all entries of all
installed ports:
.Dl % pkg updating -f /tmp/UPDATING
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-search 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-install 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-info 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xe pkg-set 8,
.Xr pkg-update 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-create 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8 ,
.Xr pkg.conf 5
