.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd January 24, 2012
.Dt PKG-UPGRADE 1
.Os
.Sh NAME
.Nm "pkg upgrade"
.Nd performs upgrades of package software distributions
.Sh SYNOPSIS
.Nm
.Op Fl y
.Sh DESCRIPTION
.Nm
is used for upgrading of package software distributions.
.Pp
Currently only one remote package repository database can be
used during package upgrades as defined by the environment variable
.Ev PACKAGESITE .
.Pp
Soon enough
.Nm
will be able to perform package upgrades from multiple repositories.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl y
Assume yes when asked for confirmation before package installation.
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr pkg.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It Ev ASSUME_ALWAYS_YES
.It Ev HANDLE_RC_SCRIPTS
.It Ev PACKAGESITE
.It Ev PKG_CACHEDIR
.It Ev PKG_DBDIR
.It Ev PKG_MULTIREPOS
.El
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg 1 ,
.Xr pkg-add 1 ,
.Xr pkg-autoremove 1 ,
.Xr pkg-search 1 ,
.Xr pkg-backup 1 ,
.Xr pkg-install 1 ,
.Xr pkg-delete 1 ,
.Xr pkg-info 1 ,
.Xr pkg-register 1 ,
.Xr pkg-repo 1 ,
.Xr pkg-update 1 ,
.Xr pkg-updating 1 ,
.Xr pkg-create 1 ,
.Xr pkg-version 1 ,
.Xr pkg-which 1 ,
.Xr pkg.conf 5
