.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd July 26, 2011
.Dt PKG-SEARCH 1
.Os
.Sh NAME
.Nm "pkg search"
.Nd searches in remote package repositories
.Sh SYNOPSIS
.Nm
.Op Fl gxXcd
.Ar pattern
.Sh DESCRIPTION
.Nm
is used for searching in a remote package repository.
.Pp
.Nm
will search for a given pattern in the remote package
repositories as defined in
.Fa /etc/pkg/repositories
.Pp
Please note that you need first to fetch/update the remote repositories
before using
.Nm
.Pp
For more information on fetching the remote package repositories
please refer to
.Xr pkg-update 1
.Pp
Multiple package repositories is activated only when the environment
variable \fBPACKAGESITE\fP is not defined. Please note that multiple remote
repositories feature is still considered highly experimental.
.Pp
If \fBPACKAGESITE\fP is defined then only the repository to which it points is
the one that is used during the package search.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl g 
Treat
.Ar pattern
as a shell glob pattern.
.It Fl x
Treat
.Ar pattern
as a regular expression.
.It Fl X
Treat 
.Ar pattern
as an extended regular expression.
.It Fl c
Search for
.Ar pattern
in the package comment one-line description.
.It Fl d
Search for
.Ar pattern
in the package desription.
.El
.Sh WARNING
.Sh ENVRIOMENT
The following envrioment variables affect the execution of
.Nm :
.Bl -tag -width ".Ev PACKAGESITE"
.It Ev PACKAGESITE
When \fBPACKAGESITE\fP is defined
.Nm
will only use the remote repository to which it points. Otherwise
.Nm
will work on multiple repositories as listed in the
.Pa /etc/pkg/repositories
file. Please note that multiple remote repositories is still considered
highly experimental.
.El
.Sh FILES
.Bl -tag -width -".Pa /etc/pkg/repositories"
.It Pa /etc/pkg/repositories
Global repositories file. This file contains a pair of
.Fa name = url
entries, each describing a remote repository, from which
.Nm
will search for the specified pattern. The file format of the file
is the same as described in
.Xr pkg.conf 5
Please refer to the included sample configuration file for example
definitions of remote repositories.
.El
.Sh FILES
.Sh SEE ALSO
pkg(1), pkg-create(1), pkg-add(1), pkg-info(1), pkg-register(1), pkg-repo(1),
pkg-upgrade(1), pkg-version(1), pkg-which(1)
.Sh AUTHORS AND CONTRIBUTORS
.Sh BUGS
