.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd Aug 23, 2011
.Dt PKG-REPOSITORIES 5
.Os
.Sh NAME
.Nm "repositories"
.Nd System-wide repositories file for
.Xr pkg 1
.Sh DESCRIPTION
This file contains the system-wide definitions
of remote repositories in
.Xr pkg 1
.Pp
The location of this file is
.Fa /etc/pkg/repositories
.Pp
Lines in the file beginning with a "#" or ";" are comments
and are ignored.
.Pp
A repository in the file is defined in the form of
.Fa name = url
.Pp
The following names of repositories cannot be used as
they are already reserved, or being used internally by
.Xr pkg 1
and thus cannot be re-defined - \fBmain\fP, \fBtemp\fP, \fBrepo\fP and \fBmemdb\fP
.Pp
When working on multiple remote repositories
.Xr pkg 1
will install a package and it's dependencies only from the 
first-matching repository.
.Pp
That is why you should always have a default repository, which is the first
defined repository. Your default repository should always be set to an
official
.Xr pkg 1
repository or a mirror of it.
.Pp
.Sh OPTIONS
The following options can be defined in
.Nm :
.Bl -tag -width F1
.El
.Sh WARNING
.Sh ENVRIOMENT
The following environment variables affect the execution of
.Xr pkg 1
.Bl -tag -width ".Ev PACKAGESITE"
.It Ev PACKAGESITE
Disables the use of multiple remote repository and switches to a
single repository use, which is the defined by the environment 
variable's value.
.El
.Sh FILES
.Sh SEE ALSO
.Xr pkg 1 ,
.Xr pkg-add 1 ,
.Xr pkg-autoremove 1 ,
.Xr pkg-search 1 ,
.Xr pkg-backup 1 ,
.Xr pkg-install 1 ,
.Xr pkg-delete 1 ,
.Xr pkg-info 1 ,
.Xr pkg-register 1 ,
.Xr pkg-repo 1 ,
.Xr pkg-update 1 ,
.Xr pkg-upgrade 1 ,
.Xr pkg-version 1 ,
.Xr pkg-which 1 ,
.Xr pkg.conf 5
.Sh AUTHORS AND CONTRIBUTORS
.Sh BUGS
