.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.8
.\" $FreeBSD$
.\"
.Dd April 15, 2013
.Dt PKG-REPO 8
.Os
.Sh NAME
.Nm "pkg repo"
.Nd creates a package repository catalogue
.Sh SYNOPSIS
.Nm
.Op Fl flq
.Ao Ar repo-path Ac Op Ar rsa-key
.Sh DESCRIPTION
.Nm
is used for creating a catalogue of the available
packages in a repository.
.Nm
catalogues are necessary for sharing your package repository with
other people.
.Pp
When
.Nm
is invoked it creates a package repository catalogue (repo.sqlite),
with an optional cryptographic signature, as a compressed tarball
(repo.txz).
Repository users download and cache this on their local machines,
for fast lookup of available packages by programs such as
.Xr pkg-install 8 .
.Pp
To create a package repository catalogue you must specify the
top-level directory where all the packages are stored as
.Ar repo-path .
.Nm
will search the filesystem beneath
.Ar repo-path
to find all the packages it contains.
Symbolic links are ignored, and only the most recent package for each
origin is included in the catalogue.
If a catalogue already exists, it will be updated incrementally with
any changes to the package collection.
This is a significant time savings for large package repositories.
.Pp
Optionally you may sign the repository catalogue by specifying the
path to an RSA private key as the
.Ar rsa-key
argument.
Signing the catalogue is strongly recommended.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl q
Force quiet output
.It Fl f
Force a full rebuild of the package catalogue, discarding any previous
content
.It Fl l
Generate list of all files in repo as filesite.txz archive.
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr pkg.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It Ev PUBKEY
.El
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg.conf 5 ,
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-annotate 8 ,
.Xr pkg-audit 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-check 8 ,
.Xr pkg-clean 8 ,
.Xr pkg-convert 8 ,
.Xr pkg-create 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-fetch 8 ,
.Xr pkg-info 8 ,
.Xr pkg-install 8 ,
.Xr pkg-lock 8 ,
.Xr pkg-query 8 ,
.Xr pkg-register 8 ,
.Xr pkg-rquery 8 ,
.Xr pkg-search 8 ,
.Xr pkg-set 8 ,
.Xr pkg-shell 8 ,
.Xr pkg-shlib 8 ,
.Xr pkg-stats 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8
