.\"
.\" FreeBSD pkg - a next generation package for the installation and
.\" maintenance of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.8
.\" $FreeBSD$
.\"
.Dd June 22, 2013
.Dt PKG-UPGRADE 8
.Os
.Sh NAME
.Nm "pkg upgrade"
.Nd performs upgrades of package software distributions
.Sh SYNOPSIS
.Nm
.Op Fl fInFqUy
.Op Fl r Ar reponame
.Sh DESCRIPTION
.Nm
is used for upgrading packaged software distributions.
.Pp
.Nm
compares the versions of all of the packages installed on the system
to what is available in the configured package repositories.
Any out-of-date packages are added to a work list for processing.
If the
.Fl f
(force) flag is given, all installed packages are added to the work
list.
.Pp
The package metadata downloaded from the repositories is then examined
for each of the packages in the work list, and any missing
dependencies are added to the work list as install jobs.
Such implicitly added packages are flagged as candidates for 
autoremoval.
See
.Xr pkg-autoremove 8
for details.
.Pp
Autoremoval flags are sticky, and will persist over reinstallation or
upgrade of the packages concerned, even if subsequently the packages
are named explicitly on a command line.
See
.Xr pkg-query 8
for finding the autoremoval status of a package, and
.Xr pkg-set 8
for modifying it.
.Pp
Where a package on the work list supplies a shared library, and that
library has been updated, all packages requiring that shared library
will also be added to the work list as reinstallation jobs.
.Pp
The work list is sorted into dependency order and
.Nm
will present it to the user for approval before proceeding, unless
overridden by the
.Fl y
option or the
.Cm ASSUME_ALWAYS_YES
setting in
.Pa pkg.conf .
.Pp
Packages are fetched from the repositories into the local package
cache if they are not already present, or if the checksum of the
cached package file differs from the one in the repository.
Packages may be downloaded from any of the repositories mentioned
in
.Xr pkg.conf 5
or in the files in
.Pa /usr/local/etc/pkg/repo .
See
.Xr pkg-repository 5
for details.
.Pp
Repository catalogues will automatically be updated whenever
.Xr pkg-update 8
is run, unless disabled by the
.Fl U
flag or setting
.Cm REPO_AUTOUPDATE
to
.Sy NO
in
.Xr pkg.conf 5 .
.Pp
Finally, the work list is executed in dependency order.
Package reinstall or update jobs are processed by removing the currently
installed package and immediately installing the replacement.
New dependencies are processed as installation jobs as part of the
work list.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl f
Force reinstalling/upgrading the whole set of packages
.It Fl I
If any installation scripts (pre-install or post-install) or deinstallation
scripts (pre-deinstall or post-deinstall) exist for a given package, do not
execute them.
.It Fl L
Backwards compatbility flag for
.Fl U .
This is planned to be removed.
.It Fl n
Dry-run mode: show what packages have updates available, but do not perform
any upgrades.
Repository catalogues will be updated as usual unless the
.Fl U
option is also given.
.It Fl F
Do not perform installation of packages, merely fetch packages that should be
upgraded and detect possible conflicts.
.It Fl q
Force quiet output, except when
.Fl n
is used, where
.It Fl U
Skip updating the repository catalogues with
.Xr pkg-update 8 .
Use the local cache only.
.Nm
will always print out the list of packages with available updates.
.It Fl y
Assume yes when asked for confirmation before package installation.
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr pkg.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It Ev ASSUME_ALWAYS_YES
.It Ev HANDLE_RC_SCRIPTS
.It Ev PACKAGESITE
.It Ev PKG_CACHEDIR
.It Ev PKG_DBDIR
.It Ev REPO_AUTOUPDATE
.El
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg.conf 5 ,
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-annotate 8 ,
.Xr pkg-audit 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-check 8 ,
.Xr pkg-clean 8 ,
.Xr pkg-convert 8 ,
.Xr pkg-create 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-fetch 8 ,
.Xr pkg-info 8 ,
.Xr pkg-install 8 ,
.Xr pkg-lock 8 ,
.Xr pkg-query 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xr pkg-rquery 8 ,
.Xr pkg-search 8 ,
.Xr pkg-set 8 ,
.Xr pkg-shell 8 ,
.Xr pkg-shlib 8 ,
.Xr pkg-stats 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8
