.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.8
.\" $FreeBSD$
.\"
.Dd February 16, 2012
.Dt PKG-SEARCH 8
.Os
.Sh NAME
.Nm "pkg search"
.Nd searches in remote package repositories
.Sh SYNOPSIS
.Nm
.Ar pkg-name
.Nm
.Op Fl fDsqop
.Ar pkg-name
.Nm
.Op Fl gexXcdfDsqop
.Ar pattern
.Sh DESCRIPTION
.Nm
is used for searching in the remote package repositories
and it displays the requested information for the matching
packages.
.Pp
.Nm
will search for the given pattern in the remote package
repositories, which are defined in the
.Xr pkg.conf 5
file.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl e
Treat
.Ar pattern
as exact pattern
.It Fl g
Treat
.Ar pattern
as a shell glob pattern.
.It Fl x
Treat
.Ar pattern
as a regular expression.
.It Fl X
Treat
.Ar pattern
as an extended regular expression.
.It Fl c
Search for
.Ar pattern
in the package comment one-line description.
.It Fl D
Search for
.Ar pattern
in the package desription.
.It Fl f
Displays full information about the matching packages.
.It Fl d
Displays the dependencies of
.Ar pattern
.It Fl s
Displays the size of the package
.It Fl q
Be ``quiet''.
Prints only the requested information without
displaying many hints.
.It Fl o
Displays
.Ar pattern
origin.
.It Fl p
Displays the installation prefix for each package matching
.Ar pattern
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr pkg.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It Ev PACKAGESITE
.It Ev PKG_MULTIREPOS
.El
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-audit 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-check 8 ,
.Xr pkg-clean 8 ,
.Xr pkg-create 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-fetch 8 ,
.Xr pkg-info 8 ,
.Xr pkg-install 8 ,
.Xr pkg-query 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xr pkg-rquery 8 ,
.Xr pkg-set 8 ,
.Xr pkg-shell 8 ,
.Xr pkg-shlib 8 ,
.Xr pkg-stats 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8 ,
.Xr pkg.conf 5
