.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.8
.\" $FreeBSD$
.\"
.Dd March 22, 2013
.Dt PKG-CHECK 8
.Os
.Sh NAME
.Nm "pkg check"
.Nd sanity checks installed packages
.Sh SYNOPSIS
.Nm
.Op Fl Bdsr
.Op Fl vyn
.Op Fl a | gix Ar <pattern>
.Sh DESCRIPTION
.Nm
.Fl B
is used to reanalyse SHLIBS of installed packages.
See
.Xr pkg.conf 5
for more information on SHLIBS.
.Pp
.Nm
.Fl d
is used to check for and install missing dependencies.
.Pp
.Nm
.Fl r
is used to recompute sizes and checksums of installed packages.
.Pp
.Nm
.Fl s
is used to find invalid checksums for installed packages.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width F1
.It Fl y
Assume yes when asked for confirmation before installing missing dependencies.
.It Fl v
Be verbose.
.It Fl n
Merely check for missing dependencies and do not install them.
.It Fl a
Process all packages.
.It Fl i
Make the standard or regular expression
.Fl ( x )
matching against
.Ar pattern
case insensitive.
.It Fl g
Treat
.Ar <pattern>
as a shell glob pattern.
.It Fl x
Treat
.Ar <pattern>
as a regular expression.
This uses the "modern" or "extended" syntax described in
.Xr re_format 7
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr pkg.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It PKG_DBDIR
.El
.Sh FILES
See
.Xr pkg.conf 5 .
.Sh SEE ALSO
.Xr pkg.conf 5 ,
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-audit 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-clean 8 ,
.Xr pkg-convert 8 ,
.Xr pkg-create 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-fetch 8 ,
.Xr pkg-info 8 ,
.Xr pkg-install 8 ,
.Xr pkg-lock 8 ,
.Xr pkg-query 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xr pkg-rquery 8 ,
.Xr pkg-search 8 ,
.Xr pkg-set 8 ,
.Xr pkg-shell 8 ,
.Xr pkg-shlib 8 ,
.Xr pkg-stats 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8
