.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd March 29, 2011
.Dt pkg
.Os
.Sh NAME
.Nm pkg
.Nd a utility for manipulating packages 
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Sh WARNING
.Sh OPTIONS
.Sh ENVRIOMENT
.Sh FILES
.Sh SEE ALSO
.Sh AUTHORS AND CONTRIBUTERS
.Sh BUGS


