.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd January 23, 2012
.Dt PKG 1
.Os
.\" ---------------------------------------------------------------------------
.Sh NAME
.Nm pkg
.Nd a utility for manipulating packages 
.\" ---------------------------------------------------------------------------
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl d
.Op Fl j Ao jail name or id Ac | Fl c Ao chroot path Ac
.Ao command Ac Ao Ar flags Ac
.\" ---------------------------------------------------------------------------
.Sh DESCRIPTION
provides an interface for manupulating packages - registering,
adding, removing and upgrading of packages.
.\" ---------------------------------------------------------------------------
.Sh OPTIONS
The following options are supported by
.Nm:
.Bl -tag -width indent
.It Fl v
Displays the current version of
.Nm
.It Fl d
Show debug informations
.It Fl j Ao jail name or id Ac
.Nm
will execute in the given
.Ao jail name or id Ac
.Xr jail 8
.It Fl c Ao chroot path Ac
.Nm
will chroot in the
.Ao chroot path Ac
Environment
.El
.\" ---------------------------------------------------------------------------
.Sh COMMANDS
The following commands are supported by
.Nm :
.Bl -tag -width indent
.It \fBhelp\fP Ar <command>
Displays usage information of the specified command.
.It \fBadd\fP
Installs a package from either a local source or a remote one.
.Pp
When installing from remote source you need to specify the
protocol to use when fetching the package.
.Pp
Currently supported protocols are FTP, HTTP and HTTPS.
.It \fBaudit\fP
????
.It \fBautoremove\fP
Deletes packages not depended on by anyother packages and that were
automatically installed.
.It \fBbackup\fP
Dumps the local package database to a file specified on the command-line.
.It \fBcheck\fP
????
.It \fBclean\fP
????
.It \fBcreate\fP
Creates a package
.It \fBdelete\fP
Deletes a package from the database and the system.
.It \fBinfo\fP
Displays information about installed packages.
.It \fBinstall\fP
Installs a package from a remote package repository.
If a package is found in more than one remote repositories,
then installation happens from the first one. If a package
fails to fetch from the remote repository the next one in
the list is tried, until the package is fetched.
.It \fBquery\fP
Is used for displaying information about packages.
.It \fBregister\fP
Registers a package in the database.
.It \fBrepo\fP
Creates a package repository.
.Pp
< To be completed >
.It \fBsearch\fP
Will search for the given pattern in the remote package
repositories.
.It \fBupdate\fP
Update the available remote repositories as listed in
.Xr pkg.conf 5 .
.It \fBupdating\fP
????
.It \fBupgrade\fP
Upgrades a package to a newer version.
.It \fBversion\fP
< To be added >
.It \fBwhich\fP
Queries the database for package(s) that installed a specific
file.
.El
.\" ---------------------------------------------------------------------------
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm :
.Bl -tag -width ".Ev PKG_DBDIR"
.It Ev PKG_DBDIR
.El
See 
.Xr pkg.conf 5
for explanation.
.\" ---------------------------------------------------------------------------
.Sh FILES
See 
.Xr pkg.conf 5
.\" ---------------------------------------------------------------------------
.Sh SEE ALSO
.Xr pkg-autoremove 1 ,
.Xr pkg-search 1 ,
.Xr pkg-backup 1 ,
.Xr pkg-install 1 ,
.Xr pkg-delete 1 ,
.Xr pkg-info 1 ,
.Xr pkg-register 1 ,
.Xr pkg-repo 1 ,
.Xr pkg-update 1 ,
.Xr pkg-upgrade 1 ,
.Xr pkg-version 1 ,
.Xr pkg-which 1 ,
.Xr pkg.conf 5
.\" ---------------------------------------------------------------------------
.Sh HISTORY
The
.Nm
command first appeared in
.Fx \" TODO: Put release there
.\" ---------------------------------------------------------------------------
.Sh AUTHORS AND CONTRIBUTORS
.An Baptiste Daroussin Aq bapt@FreeBSD.org
.An Julien Laffaye Aq jlaffaye@FreeBSD.org
.An Philippe Pepiot Aq phil@philpep.org
.An Will Andrews Aq will@FreeBSD.org
.An Marin Atanasov Nikolov Aq dnaeon@gmail.com
.\" ---------------------------------------------------------------------------
.Sh BUGS
There might be some left.
