.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.8
.\" $FreeBSD$
.\"
.Dd October 19, 2012
.Dt PKG 8
.Os
.\" ---------------------------------------------------------------------------
.Sh NAME
.Nm pkg ,
.Nm pkg-static
.Nd a utility for manipulating packages
.\" ---------------------------------------------------------------------------
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl d
.Op Fl l
.Op Fl j Ao jail name or id Ac | Fl c Ao chroot path Ac
.Ao command Ac Ao Ar flags Ac
.\" ---------------------------------------------------------------------------
.Sh DESCRIPTION
provides an interface for manupulating packages - registering,
adding, removing and upgrading of packages.
.Nm pkg-static
is a statically linked variant of
.Nm
typically only used for the initial installation of
.Nm .
There are some differences in functionality.
See
.Xr pkg.conf 5
for details.
.\" ---------------------------------------------------------------------------
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width indent
.It Fl v
Displays the current version of
.Nm
.It Fl d
Show debug information
.It Fl l
List all the available command names, and exit without performing any
other action.
The
.Fl v
option takes precedence over
.Fl l
but
.Fl l
will override any other command line arguments. 
.It Fl j Ao jail name or id Ac
.Nm
will execute in the given
.Ao jail name or id Ac ,
where
.Em name
matches
.Dq Cm jls Ar name
and
.Em id
matches
.Dq Cm jls Ar jid .
See
.Xr jail 8
and
.Xr jls 8 .
.It Fl c Ao chroot path Ac
.Nm
will chroot in the
.Ao chroot path Ac
Environment
.El
.\" ---------------------------------------------------------------------------
.Sh COMMANDS
The following commands are supported by
.Nm :
.Bl -tag -width indent
.It Ic help Ar <command>
Display usage information of the specified command.
.It Ic add
Install a package from either a local source or a remote one.
.Pp
When installing from remote source you need to specify the
protocol to use when fetching the package.
.Pp
Currently supported protocols are FTP, HTTP and HTTPS.
.It Ic audit
Audits installed packages against known vulnerabilities.
.It Ic autoremove
Delete packages which were automatically installed as dependencies and are not required any more.
.It Ic backup
Dump the local package database to a file specified on the command-line.
.It Ic check
Sanity checks installed packages.
.It Ic clean
Cleans the local cache of fetched remote packages.
.It Ic create
Create a package
.It Ic delete
Delete a package from the database and the system.
.It Ic fetch
Fetches packages from a remote repository.
.It Ic info
Display information about installed packages.
.It Ic install
Install a package from a remote package repository.
If a package is found in more than one remote repository,
then installation happens from the first one.
Downloading a package is tried from each package repository in turn,
until the package is successfully fetched.
.It Ic query
Query information about installed packages.
.It Ic register
Register a package in the database.
.It Ic repo
Create a local package repository for remote usage.
.It Ic rquery
Query information for remote repositories.
.It Ic search
Search for the given pattern in the remote package
repositories.
.It Ic set
Modify information in the installed database.
.It Ic shell
Fires up a sqlite shell to the local or remote database.
Extreme care should be taken when using this command.
.It Ic shlib
Displays which packages link to a specific shared library.
.It Ic stats
Display package database statistics.
.It Ic update
Update the available remote repositories as listed in
.Xr pkg.conf 5 .
.It Ic updating
Displays UPDATING entries of installed packages.
.It Ic upgrade
Upgrade a package to a newer version.
.It Ic version
Summarize installed versions of packages.
.It Ic which
Query the database for package(s) that installed a specific
file.
.El
.\" ---------------------------------------------------------------------------
.Sh ENVIRONMENT
The list of environment variables that affect the execution of
.Nm
is in
.Xr pkg.conf 5 .
.\" ---------------------------------------------------------------------------
.Sh FILES
See
.Xr pkg.conf 5 .
.\" ---------------------------------------------------------------------------
.Sh SEE ALSO
.Xr pkg.conf 5 ,
.Xr pkg-add 8 ,
.Xr pkg-audit 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-check 8 ,
.Xr pkg-clean 8 ,
.Xr pkg-create 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-fetch 8 ,
.Xr pkg-info 8 ,
.Xr pkg-install 8 ,
.Xr pkg-lock 8 ,
.Xr pkg-query 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xr pkg-rquery 8 ,
.Xr pkg-search 8 ,
.Xr pkg-set 8 ,
.Xr pkg-shell 8 ,
.Xr pkg-shlib 8 ,
.Xr pkg-stats 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8
.\" ---------------------------------------------------------------------------
.Sh HISTORY
The
.Nm
command first appeared in
.Fx 9.1 .
.\" ---------------------------------------------------------------------------
.Sh AUTHORS AND CONTRIBUTORS
.An Baptiste Daroussin Aq bapt@FreeBSD.org
.An Julien Laffaye Aq jlaffaye@FreeBSD.org
.An Philippe Pepiot Aq phil@philpep.org
.An Will Andrews Aq will@FreeBSD.org
.An Marin Atanasov Nikolov Aq dnaeon@gmail.com
.An Bryan Drewery Aq bryan@shatow.net
.An Matthew Seaman Aq matthew@FreeBSD.org
.\" ---------------------------------------------------------------------------
.Sh BUGS
See the issue tracker at
.Em https://github.com/pkgng/pkgng/issues
