.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd April 14, 2013
.Dt PKG.CONF 5
.Os
.Sh NAME
.Nm "pkg.conf"
.Nd System-wide configuration file for
.Xr pkg 1
.Sh DESCRIPTION
.Nm
is the system-wide configuration file used by the
.Xr pkg 1
tools.
.Pp
The default location of this file is
.Fa /usr/local/etc/pkg.conf
.Pp
Lines in the file beginning with a "#" are comments
and are ignored.
.Pp
The file is in YAML format.
For more information on the syntax of YAML,
please visit the official YAML website - http://www.yaml.org/.
.Pp
The following types of options are recognized -
boolean, string and list options.
.Pp
A boolean option is marked as enabled if one of the following values is
specified in the configuration file -
.Fa YES, TRUE
and
.Fa ON.
.Sh OPTIONS
The following options can be defined in
.Nm :
.Bl -tag -width ".Cm ASSUME_ALWAYS_YES(boolean)"
.It Cm ASSUME_ALWAYS_YES: boolean
When this option is enabled
.Xr pkg 1
will automatically assume "yes" to all questions
which require user confirmation before doing anything, as if it
the
.Fl y
flag was specified.
By default this option is disabled.
.It Cm PUBKEY: string
Specifies the location to the public RSA key used for signing the
repository database.
The default value for this file is
.Fa /etc/ssl/pkg.conf
.It Cm HANDLE_RC_SCRIPTS: boolean
This option when enabled
will automatically perform start/stop of services during package
installation and deinstallation.
Services are started on installation only
if they are enabled in
.Fa /etc/rc.conf .
By default this option is disabled.
.It Cm PACKAGESITE: string
Specifies the remote location to use
when fetching the database file and packages.
This supports using
.Sy ${ABI}
to create a dynamic URL based on the ABI being used.
.It Cm MIRROR_TYPE: string
Specifies which mirror type to use for
.Sy PACKAGESITE .
Either
.Fa HTTP
or
.Fa SRV
or
.Fa NONE
can be used.
By default
.Fa SRV
is used.
.It Cm PKG_CACHEDIR: string
Specifies the cache directory for packages.
The default value
for this option is
.Fa /var/cache/pkg
.It Cm PKG_DBDIR: string
Specifies the directory to use for storing the package
database files.
The default value for this option is
.Fa /var/db/pkg
.It Cm PLIST_KEYWORDS_DIR: string
< To be added >
.It Cm PORTSDIR: string
Specifies the location to the Ports directory.
The default value
for this option is
.Fa /usr/ports
.It Cm SYSLOG: boolean
This option is enabled by default, log all the
installation/deinstallation/upgrade operation via syslog(3)
.It Cm AUTODEPS: boolean
Analyse the elf to add dependencies (shared libraries) that may have been
forgotten by the maintainer.
default: off
.It Cm ABI: string
the abi of the package you want to install, by default the /bin/sh abi is used
.It Cm DEVELOPER_MODE: boolean
Makes certain errors immediately fatal.
Adds various warnings and
suggestions to the output of
.Xr pkg 1
as an aide to port maintainers, including indicating when the port
might be marked as architecture independent.
default: off
.It Cm PERMISSIVE: boolean
Ignore conflicts while registering a package, note that the files conflicting
will not be marked as owned by the new package. (default: NO)
.It Cm PORTAUDIT_SITE: string
Specifies the remote location to use
when fetching the portaudit database.
See
.Xr pkg-audit 8
for more information.
.It Cm DEBUG_SCRIPTS: boolean
Activate debug mode for scripts (aka set -x)
.It Cm REPO_AUTOUPDATE: boolean
When true, automatically check for and download updates to
.Fa /var/db/pkg/repo.sqlite
when running one of:
.Nm pkg upgrade ,
.Nm pkg fetch ,
.Nm pkg install
or
.Nm pkg version -R .
(default: YES)
.It Cm ENV: Key/Value list
This tells
.Xr pkg 8
to set key/values passed in the environment.
Therefore underlying libraries
like
.Xr fetch 3
can be configured (e.g. setting FTP_PROXY and HTTP_PROXY). (default: empty)
.It Cm NAMESERVER: string
Bypass name resolution forcing a nameserver
.It Cm EVENT_PIPE: string
Send all events to the specified fifo or Unix socket, events will be formatted
in JSON.
.It Cm SSH_RESTRICT_DIR: string
Directory where the ssh subsystem will be restricted to
.El
.Sh MULTIPLE REMOTE REPOSITORIES
To use multiple remote repositories, specify the primary repository as specified above.
Further remote repositores can be configured in repository files. Repository files reside in
.Fa /usr/local/etc/pkg/repos/ .
The filename does not matter,
.Fa /usr/local/etc/pkg/repos/myrepo.conf
could be used as an example. A repository file is in YAML format and has to following form (see above for the description of most options):
.Bl -tag -width ".Cm myrepo:"
.It Cm myrepo:
.Bl -tag -width ".Cm MIRROR_TYPE: string"
.It Cm URL: string
PACKAGESITE for this remote repository only.
.It Cm ENABLED: boolean
The repository will be used only if this option is enabled. (default: YES)
.It Cm MIRROR_TYPE: string
MIRROR_TYPE for this remote repository only. (default: NONE)
.It Cm PUBKEY: string
PUBKEY for this remote repository only. (default: NONE)
.El
.El
.Pp
Note that "myrepo" could be any string, however, no two repositores may share the same name. Also note that it is possible to specify more than one repository per repository file.
.Sh ENVIRONMENT
An environment variable with the same name as the option in the configuration
file always overrides the value of an option set in the file.
.Sh SEE ALSO
.Xr fetch 3 ,
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-annotate 8 ,
.Xr pkg-audit 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-check 8 ,
.Xr pkg-clean 8 ,
.Xr pkg-convert 8 ,
.Xr pkg-create 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-fetch 8 ,
.Xr pkg-info 8 ,
.Xr pkg-install 8 ,
.Xr pkg-lock 8 ,
.Xr pkg-query 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xr pkg-rquery 8 ,
.Xr pkg-search 8 ,
.Xr pkg-set 8 ,
.Xr pkg-shell 8 ,
.Xr pkg-shlib 8 ,
.Xr pkg-stats 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8
