.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd July 25, 2011
.Dt PKG 1
.Os
.Sh NAME
.Nm pkg
.Nd a utility for manipulating packages 
.Sh SYNOPSIS
.Nm
.Ar <command> Ar <flags>
.Sh DESCRIPTION
.Nm
provides an interface for manupulating packages - registering,
adding, removing and upgrading of packages.
.Sh COMMANDS
The following commands are supported by
.Nm :
.Bl -tag -width F1
.It \fBhelp\fP Ar <command>
Displays usage information of the specified command.
.It \fBadd\fP
Install a package from either a local source or a remote one.
.Pp
When installing from remote source you need to specify the
protocol to use when fetching the package.
.Pp
Currently supported protocols are FTP, HTTP and HTTPS.
.It \fBinstall\fP
Installs a package from a remote package repository.
If a package is found in more than one remote repositories,
then installation happens from the first one. If a package
fails to fetch from the remote repository the next one in
the list is tried, until the package is fetched.
.It \fBcreate\fP
Creates a package
.It \fBdelete\fP
Deletes a package from the database and the system.
.It \fBinfo\fP
Displays information about installed packages.
.It \fBregister\fP
Registers a package in the database.
.It \fBrepo\fP
Creates a package repository.
.Pp
< To be completed >
.It \fBupdate\fP
Update the available remote repositories as listed in
.Pa /etc/pkg/repositories
.It \fBupgrade\fP
Upgrades a package to a newer version.
.It \fBversion\fP
< To be added >
.It \fBwhich\fP
Queries the database for package(s) that installed a specific
file.
.El
.Sh WARNING
.Sh ENVRIOMENT
The following envrioment variables affect the execution of
.Nm :
.Bl -tag -width ".Ev TMPDIR"
.It Ev TMPDIR, SQLITE_FORCE_PROXY_LOCKING, PKG_DBDIR
.El
.Sh FILES
.Bl -tag -width ".Pa /etc/pkg.conf"
.It Pa /etc/pkg.conf
System-wide configuration file. This file format and available configuration
options are described in
.Xr pkg.conf 5 .
.El

.Bl -tag -width ".Pa /etc/pkg/repositories"
.It Pa /etc/pkg/repositories
Global repositories file. This file contains a pair of
.Fa name = url
entries, each describing a remote repository, from which
.Nm
can fetch and install packages. The file format of the file
is the same as described in
.Xr pkg.conf 5
Please refer to the included sample configuration file for example
definitions of remote repositories.
.El
.Sh SEE ALSO
.Xr pkg 1,
.Xr pkg-add 1,
.Xr pkg-autoremove 1,
.Xr pkg-backup 1,
.Xr pkg-create 1,
.Xr pkg-info 1,
.Xr pkg-install 1,
.Xr pkg-search 1,
.Xr pkg-register 1,
.Xr pkg-update 1,
.Xr pkg-upgrade 1,
.Xr pkg-version 1,
.Xr pkg-which 1,
.Xr pkg.conf 5
.Sh AUTHORS AND CONTRIBUTORS
.Sh BUGS
