.\"
.\" FreeBSD pkg - a next generation package for the installation and maintenance
.\" of non-core utilities.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)pkg.1
.\" $FreeBSD$
.\"
.Dd June 12, 2012
.Dt PKG.CONF 5
.Os
.Sh NAME
.Nm "pkg.conf"
.Nd System-wide configuration file for
.Xr pkg 1
.Sh DESCRIPTION
.Nm
is the system-wide configuration file used by the
.Xr pkg 1
tools.
.Pp
The default location of this file is
.Fa /usr/local/etc/pkg.conf
.Pp
Lines in the file beginning with a "#" are comments
and are ignored.
.Pp
The file is in YAML format.
For more information on the syntax of YAML,
please visit the official YAML website - http://www.yaml.org/.
.Pp
The following types of options are recognized -
boolean, string and list options.
.Pp
A boolean option is marked as enabled if one of the following values is
specified in the configuration file -
.Fa YES, TRUE
and
.Fa ON.
.Pp
.Sh OPTIONS
The following options can be defined in
.Nm :
.Bl -tag -width ".Cm ASSUME_ALWAYS_YES(boolean)"
.It Cm ASSUME_ALWAYS_YES: boolean
When this option is enabled
.Xr pkg 1
will automatically assume "yes" to all questions
which require user confirmation before doing anything, as if it
the
.Fl y
flag was specified.
By default this option is disabled.
.It Cm PUBKEY: string
Specifies the location to the public RSA key used for signing the
repository database.
The default value for this file is
.Fa /etc/ssl/pkg.conf
.It Cm HANDLE_RC_SCRIPTS: boolean
This option when enabled
will automatically perform start/stop of services during package
installation and deinstallation.
Services are started on installation only
if they are enabled in
.Fa /etc/rc.conf .
By default this option is disabled.
.It Cm PACKAGESITE: string
Specifies the remote location to use
when fetching the database file and packages.
.It Cm PKG_CACHEDIR: string
Specifies the cache directory for packages.
The default value
for this option is
.Fa /var/cache/pkg
.It Cm PKG_DBDIR: string
Specifies the directory to use for storing the package
database files.
The default value for this option is
.Fa /var/db/pkg
.It Cm PKG_MULTIREPOS: boolean
This option when enabled will tell
.Xr pkg 1
to work in multiple repositories mode.
For example repositories
definitions, please have a look at the sample configuration file.
.It Cm PLIST_KEYWORS_DIR: string
< To be added >
.It Cm PORTSDIR: string
Specifies the location to the Ports directory.
The default value
for this option is
.Fa /usr/ports
.It Cm SYSLOG: boolean
This option is enabled by default, log all the
installation/deinstallation/upgrade operation via syslog(3)
.It Cm SHLIBS: boolean
Analyse elf and track all shared libraries needed by the packages.
This option is silently ignored by
.Xr pkg-static 8
since it relies on
.Xr dlopen 3
which is unavailable to statically linked programs.
default: off
.It Cm AUTODEPS: boolean
Analyse the elf to add dependencies (shared libraries) that may have been
forgotten by the maintainer.
This option is silently ignored by
.Xr pkg-static 8
since it relies on
.Xr dlopen 3
which is unavailable to statically linked programs.
default: off
.It Cm ABI: string
the abi of the package you want to install, by default the /bin/sh abi is used
.It Cm DEVELOPER_MODE: boolean
Makes certain errors immediately fatal.
Adds various warnings and
suggestions to the output of
.Xr pkg 1
as an aide to port maintainers, including indicating when the port
might be marked as architecture independent.
default: off
.It Cm PORTAUDIT_SITE: string
Specifies the remote location to use
when fetching the portaudit database.
See
.Xr pkg-audit 8
for more information.
.El
.Sh ENVIRONMENT
An environment variable with the same name as the option in the configuration
file always overrides the value of an option set in the file.
.Sh SEE ALSO
.Xr pkg 8 ,
.Xr pkg-add 8 ,
.Xr pkg-audit 8 ,
.Xr pkg-autoremove 8 ,
.Xr pkg-backup 8 ,
.Xr pkg-check 8 ,
.Xr pkg-clean 8 ,
.Xr pkg-create 8 ,
.Xr pkg-delete 8 ,
.Xr pkg-fetch 8 ,
.Xr pkg-info 8 ,
.Xr pkg-install 8 ,
.Xr pkg-query 8 ,
.Xr pkg-register 8 ,
.Xr pkg-repo 8 ,
.Xr pkg-rquery 8 ,
.Xr pkg-search 8 ,
.Xr pkg-set 8 ,
.Xr pkg-shell 8 ,
.Xr pkg-shlib 8 ,
.Xr pkg-stats 8 ,
.Xr pkg-update 8 ,
.Xr pkg-updating 8 ,
.Xr pkg-upgrade 8 ,
.Xr pkg-version 8 ,
.Xr pkg-which 8
